FROM ubuntu:latest
LABEL org.opencontainers.image.authors="MykhailoKrylov s96504@pollub.edu.pl"

RUN apt update && apt install apache2 -y

COPY index.html /var/www/html/index.html
COPY ports.conf  /etc/apache2/ports.conf
EXPOSE 8081

ENTRYPOINT [ "apache2ctl" ]
CMD [ "-D", "FOREGROUND" ]